// Build-time only. Run pnpm schemas:viewer; the generated browser module never compiles schemas.
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { Ajv2020 } from "ajv/dist/2020.js";
import standaloneCode from "ajv/dist/standalone/index.js";
import { build } from "esbuild";
import { schemaFor } from "../src/schemas.ts";

export const VIEWER_VALIDATORS_PATH = fileURLToPath(new URL("../src/generated/viewer-validators.js", import.meta.url));

export async function generateViewerValidators(): Promise<string> {
  const ajv = new Ajv2020({ strict: true, allErrors: false, discriminator: true,
    validateFormats: false, unicodeRegExp: true, code: { source: true, esm: true } });
  ajv.addSchema(schemaFor("site"), "site");
  ajv.addSchema(schemaFor("changes"), "changes");
  const source = standaloneCode.default(ajv, { validateSite: "site", validateChanges: "changes" });
  const result = await build({
    stdin: { contents: source, resolveDir: fileURLToPath(new URL("..", import.meta.url)), sourcefile: "viewer-validators.static.js" },
    bundle: true, write: false, platform: "browser", format: "esm", target: "es2022",
    minify: true, legalComments: "none", charset: "utf8", logLevel: "silent",
  });
  const output = result.outputFiles[0];
  if (output === undefined) throw new Error("viewer-validator-build-empty");
  const licence = readFileSync(new URL("../node_modules/ajv/LICENSE", import.meta.url), "utf8").replaceAll("\r\n", "\n");
  return "// @ts-nocheck -- generated static Ajv validation; typed wrapper and generator are checked.\n" +
    "// GENERATED by packages/schemas/scripts/generate-viewer-validators.ts. Do not edit.\n" +
    "// Run pnpm schemas:viewer to regenerate.\n" + `/*! Bundled Ajv runtime helper licence:\n${licence}\n*/\n` + output.text;
}

if (process.argv[1] !== undefined && fileURLToPath(import.meta.url) === process.argv[1]) {
  writeFileSync(VIEWER_VALIDATORS_PATH, await generateViewerValidators());
  console.log(`wrote ${VIEWER_VALIDATORS_PATH}`);
}
