// Generates src/generated/types.ts from the JSON Schemas. Run `pnpm schemas:types` after editing
// a schema; test/generated.test.ts fails while the committed file is stale.
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { compile } from "json-schema-to-typescript";
import { DOCUMENT_KINDS, schemaFor } from "../src/schemas.ts";

export const GENERATED_TYPES_PATH = fileURLToPath(new URL("../src/generated/types.ts", import.meta.url));

const BANNER = `// GENERATED by packages/schemas/scripts/generate-types.ts from packages/schemas/schemas/*.json.
// Do not edit. Run \`pnpm schemas:types\` to regenerate.`;

/** One combined schema so shared definitions become one set of named types. */
function combinedSchema(): Record<string, unknown> {
  const defs: Record<string, unknown> = {};
  const roots: { $ref: string }[] = [];
  for (const kind of DOCUMENT_KINDS) {
    const { $defs, ...root } = schemaFor(kind) as Record<string, unknown> & {
      $defs: Record<string, unknown>;
    };
    delete root["$schema"];
    for (const [name, def] of Object.entries($defs)) {
      if (name in defs && JSON.stringify(defs[name]) !== JSON.stringify(def)) {
        throw new Error(`conflicting definitions for ${name}`);
      }
      defs[name] = def;
    }
    const title = String(root["title"]);
    defs[title] = root;
    roots.push({ $ref: `#/$defs/${title}` });
  }
  return { title: "PixelWatchDocument", oneOf: roots, $defs: defs };
}

export async function generateTypes(): Promise<string> {
  return compile(combinedSchema(), "PixelWatchDocument", {
    bannerComment: BANNER,
    additionalProperties: false,
    declareExternallyReferenced: true,
    unreachableDefinitions: true,
    strictIndexSignatures: true,
    unknownAny: true,
    ignoreMinAndMaxItems: true,
    format: true,
    style: { printWidth: 100, singleQuote: false, trailingComma: "all", endOfLine: "lf" },
    $refOptions: { resolve: { external: false } },
  });
}

if (process.argv[1] !== undefined && fileURLToPath(import.meta.url) === process.argv[1]) {
  writeFileSync(GENERATED_TYPES_PATH, await generateTypes());
  console.log(`wrote ${GENERATED_TYPES_PATH}`);
}
