// Trusted ZIP reader (M1.4; 02 §5; ADR 0008; threat-model R4.3-08, R4.3-10). The hostile corpus
// in testdata/zip/hostile/ is generated by tools/zip-corpus/generate.ts; the archives here are
// built with the independent test-side writer in tools/zip-corpus/zip-builder.ts.
import { readFileSync, readdirSync } from "node:fs";
import { join } from "node:path";
import { crc32, deflateRawSync } from "node:zlib";
import fc from "fast-check";
import { UNIT_FILE_PATTERN } from "@pixelwatch/schemas";
import { describe, expect, it } from "vitest";
import { REQUIRED_CLASSES, hostileCorpus } from "../../../tools/zip-corpus/generate.ts";
import { type EntrySpec, ascii, buildZip, pngName } from "../../../tools/zip-corpus/zip-builder.ts";
import { IngressError } from "../src/ingest/errors.ts";
import { INGEST_LIMITS, IngestBudget } from "../src/ingest/limits.ts";
import { type ZipArchive, openZip, readEntry } from "../src/ingest/zip.ts";

const HOSTILE = join(import.meta.dirname, "..", "..", "..", "testdata", "zip", "hostile");
const MiB = 1024 * 1024;

interface Manifest {
  cases: { file: string; code: string; class: string; why: string }[];
}

const BUNDLE: EntrySpec = { name: "bundle.json", data: ascii('{"schemaVersion":1}') };
function png(i: number, overrides: Partial<EntrySpec> = {}): EntrySpec {
  return { name: pngName(i), data: Uint8Array.from({ length: 100 + i }, (_, k) => (k * 31 + i) & 0xff), ...overrides };
}

async function outcome(work: Promise<unknown>): Promise<string> {
  try {
    await work;
    return "ok";
  } catch (error) {
    if (error instanceof IngressError) return error.code;
    throw error;
  }
}

/** openZip as a promise, so a synchronous refusal reads like an asynchronous one. */
function opened(bytes: Uint8Array, budget = new IngestBudget(), options: { signal?: AbortSignal } = {}): Promise<ZipArchive> {
  return Promise.resolve().then(() => openZip(bytes, budget, options));
}

/** Opens and fully extracts an archive, recording every entry-buffer allocation. */
async function extractAll(bytes: Uint8Array, budget = new IngestBudget(), allocations: number[] = [], signal?: AbortSignal): Promise<Map<string, Uint8Array>> {
  const archive = openZip(bytes, budget);
  const out = new Map<string, Uint8Array>();
  for (const entry of archive.entries) {
    out.set(entry.name, await readEntry(archive, entry.name, { signal, allocate: (n) => (allocations.push(n), new Uint8Array(n)) }));
  }
  return out;
}

describe("hostile ZIP corpus (02 §5)", () => {
  const manifest = JSON.parse(readFileSync(join(HOSTILE, "manifest.json"), "utf8")) as Manifest;

  it("rejects every hostile ZIP with its code, allocating only capped declared-size entry buffers", async () => {
    for (const c of manifest.cases) {
      const bytes = readFileSync(join(HOSTILE, c.file));
      const allocations: number[] = [];
      const started = performance.now();
      expect(await outcome(extractAll(bytes, new IngestBudget(), allocations)), `${c.file}: ${c.why}`).toBe(c.code);
      for (const n of allocations) expect(n, `${c.file}: entry buffer size`).toBeLessThanOrEqual(INGEST_LIMITS.maxPngBytes);
      expect(performance.now() - started, `${c.file}: rejection time`).toBeLessThan(c.class === "deflate-bomb" ? 15_000 : 2_000);
    }
  });

  it("covers every class of hostile archive the threat model names", () => {
    const classes = new Set(manifest.cases.map((c) => c.class));
    for (const cls of REQUIRED_CLASSES) expect(classes, cls).toContain(cls);
    const codes = new Set(manifest.cases.map((c) => c.code));
    for (const code of [
      "zip-name-traversal", "zip-name-absolute", "zip-name-drive", "zip-name-separator", "zip-name-dot", "zip-name-nul",
      "zip-name-encoding", "zip-duplicate-name", "zip-name-collision", "zip-name-not-allowed", "zip-bundle-missing",
      "zip-link", "zip-special-file", "zip64", "zip-encrypted", "zip-method", "zip-header-mismatch", "zip-data-descriptor",
      "zip-overlap", "zip-gap", "zip-leading-bytes", "zip-trailing-bytes", "zip-comment", "zip-extra-field", "zip-crc",
      "zip-inflate-overflow", "zip-expanded-total", "zip-too-many-entries", "zip-entry-too-large",
    ]) {
      expect(codes, code).toContain(code);
    }
  });

  it("lists every committed corpus file in the manifest exactly once", () => {
    const files = readdirSync(HOSTILE).filter((f) => f.endsWith(".zip")).sort();
    const listed = manifest.cases.map((c) => c.file).sort();
    expect(listed).toEqual(files);
    expect(new Set(listed).size).toBe(listed.length);
    // The committed files are exactly what the generator writes: nothing was hand-edited.
    const generated = hostileCorpus();
    expect(generated.map((c) => `${c.name}.zip`).sort()).toEqual(files);
    for (const c of generated) expect(Buffer.from(c.bytes).equals(readFileSync(join(HOSTILE, `${c.name}.zip`))), c.name).toBe(true);
  }, 30_000);

  it("bounds error messages and keeps hostile bytes out of them", async () => {
    for (const c of manifest.cases) {
      try {
        await extractAll(readFileSync(join(HOSTILE, c.file)));
        expect.unreachable(c.file);
      } catch (error) {
        expect(error).toBeInstanceOf(IngressError);
        const message = (error as IngressError).message;
        expect(Buffer.byteLength(message), c.file).toBeLessThanOrEqual(2048);
        for (const hostile of ["<", "..", "\\", "evil", "server", "MZ", "index.html", "bundlé"]) expect(message, `${c.file}: ${hostile}`).not.toContain(hostile);
      }
    }
  });
});

describe("entry names (02 §5; R4.3-10)", () => {
  it("rejects any entry name but bundle.json and <viewId>.<variantId>.png", async () => {
    const suspicious = fc.oneof(
      fc.constantFrom(
        "index.html", "a.svg", "app.js", "x.css", "d.xml", "app.js.map", "n.har", "trace.zip", "bundle.json.png", "Bundle.json",
        "bundle.JSON", "bundle.json ", " bundle.json", "bundle.json.", "home.png", "home.desktop.PNG", "home.desktop.png.html",
        "Home.desktop.png", "home..png", ".desktop.png", "home.desktop.x.png", `${"a".repeat(65)}.desktop.png`, `${pngName(1)}\0`, `./${pngName(1)}`,
        "bundle.json/", "con", "aux.png", "~bundle.json", ".bundle.json",
      ),
      fc.string({ unit: fc.constantFrom(..."abu-_.0123456789fjsonpg/\\:\0 ".split("")), maxLength: 80 }),
      fc.string({ unit: "binary-ascii", maxLength: 80 }),
    );
    await fc.assert(
      fc.asyncProperty(suspicious, async (name) => {
        const allowed = name === "bundle.json" || UNIT_FILE_PATTERN.test(name);
        const entries = name === "bundle.json" ? [BUNDLE, png(1)] : [BUNDLE, { name, data: ascii("x") }];
        const result = await outcome(extractAll(buildZip({ entries })));
        if (allowed) expect(result).toBe("ok");
        else expect(result, JSON.stringify(name)).toMatch(/^zip-(name-|duplicate-name$|bundle-missing$)/);
      }),
      { numRuns: 400 },
    );
  });
});

describe("expanded-size accounting (02 §5)", () => {
  it("budgets declared sizes and holds inflation to them", async () => {
    // Header claims less than the data: the budget counts the claim, and extraction stops there.
    const lying = new IngestBudget();
    const small = buildZip({ entries: [BUNDLE, png(1, { data: new Uint8Array(8 * MiB), size: 1000 })] });
    expect(await outcome(extractAll(small, lying))).toBe("zip-inflate-overflow");
    expect(lying.expandedBytes).toBe(BUNDLE.data.length + 1000);

    // Header claims more than the data: refused when the stream ends short.
    const entry = png(1);
    expect(await outcome(extractAll(buildZip({ entries: [BUNDLE, { ...entry, size: 20 * MiB }] })))).toBe("zip-inflate-short");

    // A valid archive is charged exactly its entry sizes, before anything is inflated.
    const exact = new IngestBudget();
    const entries = [BUNDLE, png(1), png(2), png(3, { method: 0, descriptor: false })];
    openZip(buildZip({ entries }), exact);
    expect(exact.expandedBytes).toBe(entries.reduce((sum, e) => sum + e.data.length, 0));
    expect(exact.entries).toBe(4);
  });

  it("shares the 4096-entry and 512 MiB budgets across every archive of one ingestion", async () => {
    const many = (count: number, from: number) => buildZip({ entries: [BUNDLE, ...Array.from({ length: count - 1 }, (_, i) => ({ name: pngName(from + i), data: Uint8Array.of(i & 0xff) }))] });
    // Real entries, not a lying EOCD count.
    expect(await outcome(opened(many(4096, 0)))).toBe("ok");
    expect(await outcome(opened(many(4097, 0)))).toBe("zip-too-many-entries");
    const entries = new IngestBudget();
    expect(await outcome(opened(many(2048, 0), entries))).toBe("ok");
    expect(await outcome(opened(many(2048, 10_000), entries))).toBe("ok");
    expect(await outcome(opened(many(1, 20_000), entries))).toBe("zip-too-many-entries");

    // 2 × 9 honest 32 MiB entries: each archive fits, the second pushes the ingestion past 512 MiB.
    const zeros = new Uint8Array(32 * MiB);
    const compressed = deflateRawSync(zeros);
    const big = (from: number) => buildZip({ entries: [BUNDLE, ...Array.from({ length: 9 }, (_, i) => ({ name: pngName(from + i), data: zeros, compressed }))] });
    const bytes = new IngestBudget();
    expect(await outcome(opened(big(0), bytes))).toBe("ok");
    expect(bytes.expandedBytes).toBe(9 * 32 * MiB + BUNDLE.data.length);
    expect(await outcome(opened(big(100), bytes))).toBe("zip-expanded-total");
    expect(bytes.expandedBytes).toBe(9 * 32 * MiB + BUNDLE.data.length);
  });

  it("refuses an archive over 128 MiB before parsing it", async () => {
    const huge = new Uint8Array(INGEST_LIMITS.maxArchiveBytes + 1);
    huge.set(buildZip({ entries: [BUNDLE, png(1)] }));
    expect(await outcome(opened(huge))).toBe("zip-archive-too-large");
  });
});

describe("accepted layouts (ADR 0008)", () => {
  it("accepts upload-artifact's layout: data descriptors, Unix modes, deflate", async () => {
    const entries = [BUNDLE, png(1), png(2)];
    const bytes = buildZip({ entries });
    // The builder really wrote GitHub's layout: bit 3, zero local CRC/sizes, 0x81A40020.
    const view = new DataView(bytes.buffer, bytes.byteOffset, bytes.byteLength);
    expect(view.getUint16(6, true) & 0x08).toBe(0x08);
    expect([view.getUint32(14, true), view.getUint32(18, true), view.getUint32(22, true)]).toEqual([0, 0, 0]);
    const archive = openZip(bytes, new IngestBudget());
    expect(archive.entries.map((e) => [e.name, e.method, e.size])).toEqual(entries.map((e) => [e.name, 8, e.data.length]));
    for (const e of entries) expect(await readEntry(archive, e.name as string)).toEqual(e.data);
  });

  it("accepts stored entries and archives without descriptors", async () => {
    const entries = [
      { ...BUNDLE, method: 0, descriptor: false },
      png(1, { method: 0 }),
      png(2, { descriptor: false, versionMadeBy: 0x0014, externalAttrs: 0x20 }),
      png(3, { data: new Uint8Array(0) }),
    ];
    const files = await extractAll(buildZip({ entries }));
    for (const e of entries) expect(files.get(e.name as string)).toEqual(e.data);
  });

  it("extracts every entry byte-exactly", async () => {
    const entry = fc.record({
      data: fc.oneof(fc.uint8Array({ maxLength: 3000 }), fc.integer({ min: 0, max: 200_000 }).map((n) => new Uint8Array(n).fill(7))),
      method: fc.constantFrom(0, 8),
      descriptor: fc.boolean(),
    });
    await fc.assert(
      fc.asyncProperty(fc.array(entry, { minLength: 0, maxLength: 6 }), fc.integer({ min: 0, max: 7 }), async (specs, at) => {
        const entries: EntrySpec[] = specs.map((s, i) => ({ name: pngName(i), ...s }));
        entries.splice(Math.min(at, entries.length), 0, BUNDLE);
        const files = await extractAll(buildZip({ entries }));
        expect([...files.keys()]).toEqual(entries.map((e) => e.name));
        // Buffer#equals, not toEqual: a deep compare of 200 KB arrays dominates the run time.
        for (const e of entries) expect(Buffer.from(e.data).equals(files.get(e.name as string) ?? new Uint8Array(1))).toBe(true);
      }),
      { numRuns: 100 },
    );
  });

  it("verifies size and CRC when extracting", async () => {
    const bytes = buildZip({ entries: [BUNDLE, png(1, { method: 0 })] });
    const archive: ZipArchive = openZip(bytes, new IngestBudget());
    const entry = archive.entries.find((e) => e.name === pngName(1));
    if (entry === undefined) throw new Error("missing entry");
    bytes[entry.dataOffset] = (bytes[entry.dataOffset] ?? 0) ^ 0xff; // the caller's buffer changes after opening
    expect(await outcome(readEntry(archive, pngName(1)))).toBe("zip-crc");
    expect(await outcome(readEntry(archive, "missing.png"))).toBe("zip-entry-missing");
  });

  it("never fails with anything but an IngressError on corrupted archives", async () => {
    const base = buildZip({ entries: [BUNDLE, png(1), png(2, { method: 0, descriptor: false }), png(3)] });
    const mutation = fc.oneof(
      fc.array(fc.tuple(fc.nat({ max: base.length - 1 }), fc.integer({ min: 0, max: 255 })), { minLength: 1, maxLength: 8 }).map((flips) => {
        const out = Uint8Array.from(base);
        for (const [at, value] of flips) out[at] = value;
        return out;
      }),
      fc.nat({ max: base.length - 1 }).map((n) => base.subarray(0, n)),
      fc.tuple(fc.nat({ max: base.length }), fc.uint8Array({ minLength: 1, maxLength: 64 })).map(([at, extra]) => {
        const out = new Uint8Array(base.length + extra.length);
        out.set(base.subarray(0, at));
        out.set(extra, at);
        out.set(base.subarray(at), at + extra.length);
        return out;
      }),
    );
    await fc.assert(
      fc.asyncProperty(mutation, async (bytes) => {
        const result = await outcome(extractAll(bytes));
        expect(typeof result).toBe("string");
      }),
      { numRuns: 500, seed: 0x4d14 },
    );
  });

  it("stops between chunks when the signal aborts", async () => {
    const already = new AbortController();
    already.abort();
    expect(await outcome(opened(buildZip({ entries: [BUNDLE, png(1)] }), new IngestBudget(), { signal: already.signal }))).toBe("ingest-aborted");

    const zeros = new Uint8Array(32 * MiB);
    const compressed = deflateRawSync(zeros);
    const slow = buildZip({ entries: [BUNDLE, ...Array.from({ length: 15 }, (_, i) => ({ name: pngName(i), data: zeros, compressed }))] });
    const allocations: number[] = [];
    expect(await outcome(extractAll(slow, new IngestBudget(), allocations, AbortSignal.timeout(30)))).toBe("ingest-aborted");
    // Stopped part-way: not every entry was extracted.
    expect(allocations.length).toBeLessThan(16);
  });
});

describe("crc32", () => {
  it("is node:zlib's CRC-32 (the reader and the test writer share only this primitive)", () => {
    expect(crc32(ascii("123456789"))).toBe(0xcbf43926);
  });
});
