import assert from "node:assert/strict";
import {createHash} from "node:crypto";
import {mkdirSync,mkdtempSync,readFileSync,rmSync,writeFileSync} from "node:fs";
import {tmpdir} from "node:os";
import {join} from "node:path";
import {describe,it} from "vitest";
import {renderReportCaller,validateReportCaller,verifyReviewedReportWorkflow,verifyReportWorkflowTree,REVIEWED_REPORT_WORKFLOW_SHA256,type ReportCallerRelease} from "./workflow-policy.ts";
import {assertNoSecrets,CANARY_TOKEN} from "../simulation/capture.ts";

const release:ReportCallerRelease={releaseCommit:"a".repeat(40),version:"0.1.0-rc.2"},encode=(text:string)=>new TextEncoder().encode(text);
function caller(older=false):string{return `name: PixelWatch Report${older?" Older":""}\non:${older?"":" # zizmor: ignore[dangerous-triggers] ADR 0032: exact pinned caller; structural gate required"}\n${older?"":"  workflow_run:\n    workflows: [PixelWatch Capture]\n    types: [completed]\n"}  workflow_dispatch:\npermissions: {}\njobs:\n  report:\n    permissions:\n      actions: read\n      contents: write\n      pages: write\n      id-token: write\n      pull-requests: write\n    uses: MattShelton04/PixelWatch/.github/workflows/report.yml@${release.releaseCommit} # v${release.version}\n`;}
function refused(operation:()=>unknown):void {assert.throws(operation,error=>{assert.ok(error instanceof Error);assert.equal(error.message,"workflow-policy: reviewed-contract-refused");assert.equal(Object.hasOwn(error,"cause"),false);assertNoSecrets([error.message]);return true;});}
function valid():void {assert.equal(renderReportCaller(release),caller());assert.deepEqual(validateReportCaller(encode(caller()),release),release);}
describe("exact reviewed workflow development policy (no runtime or live approval)",()=>{
  it("current caller is exactly one fixed pinned reusable job with a local trigger annotation",()=>{valid();const text=renderReportCaller(release);assert.equal((text.match(/zizmor: ignore/g)??[]).length,1);assert.doesNotMatch(text,/^\s+steps:|^\s+run:|^\s+with:|secrets:|checkout@|cache@/m);});
  it("manual older caller has the same exact permission union and no trigger annotation",()=>{valid();assert.equal(renderReportCaller(release,true),caller(true));assert.deepEqual(validateReportCaller(encode(caller(true)),release,true),release);assert.doesNotMatch(caller(true),/workflow_run|zizmor:/);});
  it("added triggers run checkout cache jobs secret forwarding foreign or moving pins and duplicate fields refuse",()=>{valid();for(const text of [caller().replace("  workflow_run:","  pull_request_target:"),caller()+"  hostile:\n    runs-on: ubuntu-latest\n    steps:\n      - run: echo bad\n",caller()+"  hostile:\n    runs-on: ubuntu-latest\n    steps:\n      - uses: actions/checkout@"+"b".repeat(40)+"\n",caller()+"  hostile:\n    runs-on: ubuntu-latest\n    steps:\n      - uses: actions/cache@"+"b".repeat(40)+"\n",caller().replace("    uses:","    secrets: inherit\n    uses:"),caller().replace("MattShelton04/PixelWatch/","attacker/PixelWatch/"),caller().replace(release.releaseCommit,"main"),caller().replace("permissions: {}","permissions: {}\npermissions: write-all"),caller().replace("on:","on:\n  issue_comment:"),caller().replace("      contents: write","      contents: read"),caller().replace("    uses:","    with:\n      script: echo bad\n    uses:")])refused(()=>validateReportCaller(encode(text),release));});
  it("unknown pins versions fields accessors and proxies refuse without evaluating token-looking values",()=>{valid();for(const value of [{...release,releaseCommit:""},{...release,releaseCommit:"main"},{...release,releaseCommit:"a".repeat(7)},{...release,version:"latest"},{...release,version:"0.1.0-rc.0"},{...release,token:CANARY_TOKEN}])refused(()=>renderReportCaller(value));let callbacks=0;const accessor=Object.defineProperty({...release},"releaseCommit",{get(){callbacks++;throw new Error(CANARY_TOKEN);}}),proxy=new Proxy({...release},{ownKeys(){callbacks++;throw new Error(CANARY_TOKEN);}});refused(()=>renderReportCaller(accessor));refused(()=>renderReportCaller(proxy));assert.equal(callbacks,0);});
  it("the supplied reviewed workflow digest binds every source byte and rejects harmful scheduling or code changes",()=>{valid();const bytes=new Uint8Array(readFileSync(new URL("../../.github/workflows/report.yml",import.meta.url))),digest=createHash("sha256").update(bytes).digest("hex");verifyReviewedReportWorkflow(bytes,digest);const source=new TextDecoder().decode(bytes);for(const changed of [source.replace("steps.self.outputs.sha","github.sha"),source.replace("steps.self.outputs.repository","github.repository"),source.replace("if [ \"$own_head\" != \"$PIXELWATCH_WORKFLOW_SHA\" ]; then","if false; then"),source.replace("pixelwatch-project-${{ github.repository_id }}","pixelwatch-project-${{ github.workflow_sha }}"),source.replace("cancel-in-progress: false","cancel-in-progress: true"),source.replace("needs.ingest.result == 'success' && needs.ingest.outputs.project == 'true'","always()"),source.replace("uses: ./_pixelwatch/actions/publish","uses: ./actions/publish"),source+"# added cache restore\n"]){assert.notEqual(changed,source);refused(()=>{verifyReviewedReportWorkflow(encode(changed),digest);});}});
  it("native bytes and fixed bounds refuse oversized shared or detached inputs before callbacks",()=>{valid();const bytes=encode(caller());let callbacks=0;for(const key of ["byteLength","buffer","subarray","constructor"])Object.defineProperty(bytes,key,{get(){callbacks++;throw new Error(CANARY_TOKEN);}});assert.deepEqual(validateReportCaller(bytes,release),release);assert.equal(callbacks,0);refused(()=>validateReportCaller(new Uint8Array(65537),release));refused(()=>validateReportCaller(new Uint8Array(new SharedArrayBuffer(16)),release));const detached=encode(caller());structuredClone(detached.buffer,{transfer:[detached.buffer]});refused(()=>validateReportCaller(detached,release));});
  it("the development consumer accepts reviewed source then refuses an actual file mutation without rebinding its literal",()=>{
    const root=mkdtempSync(join(tmpdir(),"pw-workflow-policy-"));try{const directory=join(root,".github","workflows"),path=join(directory,"report.yml"),bytes=readFileSync(new URL("../../.github/workflows/report.yml",import.meta.url));mkdirSync(directory,{recursive:true});writeFileSync(path,bytes,{flag:"wx"});verifyReportWorkflowTree(root);
      const original=bytes.toString("utf8"),changed=original.replace("cancel-in-progress: false","cancel-in-progress: true");assert.notEqual(changed,original);writeFileSync(path,changed);const literal=REVIEWED_REPORT_WORKFLOW_SHA256;refused(()=>{verifyReportWorkflowTree(root);});assert.equal(REVIEWED_REPORT_WORKFLOW_SHA256,literal);
      assert.match(readFileSync(new URL("./workflow-policy.ts",import.meta.url),"utf8"),/export const REVIEWED_REPORT_WORKFLOW_SHA256 = "[0-9a-f]{64}";/);
    }finally{rmSync(root,{recursive:true,force:true});}
  });
  it("the development consumer refuses over-bound source and ignores environment attempts to substitute an unsafe digest",()=>{
    const root=mkdtempSync(join(tmpdir(),"pw-workflow-policy-"));try{const directory=join(root,".github","workflows"),path=join(directory,"report.yml");mkdirSync(directory,{recursive:true});writeFileSync(path,readFileSync(new URL("../../.github/workflows/report.yml",import.meta.url)),{flag:"wx"});verifyReportWorkflowTree(root);writeFileSync(path,"permissions: write-all\n");
      const previous=process.env;let callbacks=0;process.env=new Proxy(previous,{get(target,key){if(key==="PIXELWATCH_REPORT_SHA256"||key==="GH_TOKEN"||key==="GITHUB_TOKEN"){callbacks++;throw new Error(CANARY_TOKEN);}const value:unknown=Reflect.get(target,key);return value;}});try{refused(()=>{verifyReportWorkflowTree(root);});}finally{process.env=previous;}assert.equal(callbacks,0);writeFileSync(path,new Uint8Array(65537));refused(()=>{verifyReportWorkflowTree(root);});
    }finally{rmSync(root,{recursive:true,force:true});}
  });
});
