import assert from "node:assert/strict";
import {inspect} from "node:util";
import {mkdirSync,writeFileSync} from "node:fs";
import {afterAll,describe,it} from "vitest";
import {canonicalBytes} from "../../packages/schemas/src/index.ts";
import type {HttpRequest,HttpResponse,HttpTransport,Timing} from "../../packages/forge-github/src/transport.ts";
import {CANARY_TOKEN,SIGNED_URL,assertNoSecrets} from "../simulation/capture.ts";
import {LiveInfrastructurePreflight,type LivePreflightOptions} from "./preflight.ts";
import type {LiveSetupManifest} from "./manifest.ts";

const organization="pixelwatch-e2e",prefix=`https://api.github.com/repos/${organization}/pixelwatch-m2-live`,forkPrefix=`https://api.github.com/repos/${organization}/pixelwatch-m2-live-fork`,bot="pixelwatch-e2e-bot",sha=(character:string)=>character.repeat(40);
const policyPath=`${prefix}/environments/github-pages/deployment-branch-policies?per_page=100&page=1`,raw:string[]=[];
function fixture():LiveSetupManifest {return {schemaVersion:1,driverSourceSha:sha("a"),organization:{login:organization,id:"10"},upstream:{name:"pixelwatch-m2-live",id:"20",ownerId:"10",defaultBranch:"main",visibility:"public"},fork:{name:"pixelwatch-m2-live-fork",id:"21",ownerId:"10",defaultBranch:"main",visibility:"public",fork:true,parentId:"20",sourceId:"20"},bot:{login:bot,id:"11"},workflows:{source:{id:"30",path:".github/workflows/pixelwatch-capture.yml"},report:{id:"31",path:".github/workflows/pixelwatch-report.yml"}},pages:{url:`https://${organization}.github.io/pixelwatch-m2-live/`,prefix:"pixelwatch",environment:{id:"40",name:"github-pages",protectedBranches:false,customBranchPolicies:true,policies:[{name:"main",type:"branch"}]}},publisher:{current:{version:"0.1.0-rc.2",sourceCommit:sha("b"),releaseCommit:sha("c")},older:{version:"0.1.0-rc.1",sourceCommit:sha("d"),releaseCommit:sha("e")}},approvedRefs:["same-repo","fork","fork-hostile","full-rerun","partial-rerun","stale-head","deploy-repair","older-pin"].map(name=>`refs/heads/pixelwatch-e2e/m2/${name}`)};}
const owner=()=>({id:10,login:organization,type:"Organization"}),repo=(name:string,id:number,fork=false)=>({id,name,full_name:`${organization}/${name}`,owner:owner(),private:false,visibility:"public",default_branch:"main",fork});
const json=(status:number,value:unknown,headers:Readonly<Record<string,string>>={}):HttpResponse=>({status,headers,body:canonicalBytes(value)});
class Clock implements Timing {
  readonly handles:{controller:AbortController;ms:number;disposed:boolean}[]=[];readonly delays:number[]=[];
  deadline(ms:number){const entry={controller:new AbortController(),ms,disposed:false};this.handles.push(entry);return {signal:entry.controller.signal,dispose:()=>{assert.equal(entry.disposed,false);entry.disposed=true;}};}
  delay(ms:number):Promise<void>{this.delays.push(ms);return Promise.resolve();}
  clean():void{assert.ok(this.handles.every(handle=>handle.disposed));}
}
class World implements HttpTransport {
  readonly requests:HttpRequest[]=[];readonly clock=new Clock();readonly overrides=new Map<string,(request:HttpRequest)=>Promise<HttpResponse>>();
  response(url:string):HttpResponse {
    if(url===`https://api.github.com/orgs/${organization}`)return json(200,{id:10,login:organization,type:"Organization"});
    if(url===prefix)return json(200,repo("pixelwatch-m2-live",20));
    if(url===forkPrefix)return json(200,{...repo("pixelwatch-m2-live-fork",21,true),parent:repo("pixelwatch-m2-live",20),source:repo("pixelwatch-m2-live",20)});
    if(url===`https://api.github.com/users/${bot}`||url==="https://api.github.com/user")return json(200,{id:11,login:bot,type:"User"});
    if(url===`${prefix}/actions/workflows/30`)return json(200,{id:30,path:".github/workflows/pixelwatch-capture.yml",state:"active"});
    if(url===`${prefix}/actions/workflows/31`)return json(200,{id:31,path:".github/workflows/pixelwatch-report.yml",state:"active"});
    if(url===`${prefix}/pages`)return json(200,{html_url:`https://${organization}.github.io/pixelwatch-m2-live/`,build_type:"workflow",cname:null,https_enforced:true,public:true});
    if(url===`${prefix}/environments/github-pages`)return json(200,{id:40,name:"github-pages",deployment_branch_policy:{protected_branches:false,custom_branch_policies:true}});
    if(url===policyPath)return json(200,{total_count:1,branch_policies:[{id:41,name:"main",type:"branch"}]});
    if(url===`${prefix}/git/ref/heads/main`)return json(200,{ref:"refs/heads/main",object:{type:"commit",sha:sha("f")}});
    if(url===`${forkPrefix}/git/ref/heads/main`)return json(200,{ref:"refs/heads/main",object:{type:"commit",sha:sha("9")}});
    throw new Error("unexpected fixed preflight path");
  }
  request(request:HttpRequest):Promise<HttpResponse>{this.requests.push(request);assert.equal(request.method,"GET");assert.equal(request.maxBytes,1024*1024);assert.equal(new URL(request.url).origin,"https://api.github.com");assert.equal(request.body,undefined);return this.overrides.get(request.url)?.(request)??Promise.resolve(this.response(request.url));}
  client(credential?:string):LiveInfrastructurePreflight{return new LiveInfrastructurePreflight(canonicalBytes(fixture()),organization,{transport:this,timing:this.clock,...(credential===undefined?{}:{credential})});}
  change(url:string,mutate:(value:Record<string,unknown>)=>void):void {const value=JSON.parse(new TextDecoder().decode(this.response(url).body)) as Record<string,unknown>;mutate(value);this.overrides.set(url,()=>Promise.resolve(json(200,value)));}
}
function capture(value:unknown):void {const text=inspect(value,{showHidden:true,depth:8});assertNoSecrets([text]);raw.push(text);}
function nativeHook(name:string):symbol {let prototype:object|null=AbortSignal.prototype;while(prototype!==null){const found=Object.getOwnPropertySymbols(prototype).find(symbol=>symbol.description===name);if(found!==undefined)return found;prototype=Object.getPrototypeOf(prototype) as object|null;}throw new Error("native-hook-missing");}
async function refused(operation:()=>Promise<unknown>):Promise<void>{await assert.rejects(operation,error=>{assert.ok(error instanceof Error);capture(error);assert.equal(error.message,"live-preflight: preflight-refused");assert.equal(Object.hasOwn(error,"cause"),false);return true;});}
async function baseline():Promise<void>{const w=new World(),result=await w.client().read();assert.equal(result.upstreamHead,sha("f"));assert.equal(result.forkHead,sha("9"));w.clock.clean();capture(result);}
afterAll(()=>{assertNoSecrets(raw);const directory=new URL("../../.tools/logs/",import.meta.url);mkdirSync(directory,{recursive:true});writeFileSync(new URL("live-preflight-raw.json",directory),JSON.stringify({localOnly:true,liveResources:false,outputs:raw}));writeFileSync(new URL("live-preflight-raw-scan.json",directory),JSON.stringify({values:raw.length,bytes:raw.reduce((sum,text)=>sum+Buffer.byteLength(text),0),failures:0}));});

describe("fixed live infrastructure read-only preflight (no resource or mutation authorization)",()=>{
  it("fresh fixed public identities policy and both main heads return privately owned read-only proof",async()=>{const w=new World(),result=await w.client().read();assert.deepEqual(result.manifest,fixture());assert.equal(result.driverCredential,"not-supplied");assert.equal(result.readyForMutations,false);assert.equal(result.getAttempts,11);assert.equal(w.requests.length,11);assert.equal(result.upstreamHead,sha("f"));assert.equal(result.forkHead,sha("9"));assert.ok(Object.isFrozen(result));assert.ok(Object.isFrozen(result.manifest.pages.environment.policies));assert.ok(w.requests.every(request=>request.headers["authorization"]===undefined));w.clock.clean();capture(result);});
  it("only fixed authenticated user receives an explicit credential and proves the configured machine account",async()=>{await baseline();const w=new World(),result=await w.client(CANARY_TOKEN).read();assert.equal(result.driverCredential,"verified");assert.equal(result.readyForMutations,false);assert.equal(result.getAttempts,12);assert.equal(w.requests.filter(request=>request.url==="https://api.github.com/user").length,1);for(const request of w.requests)assert.equal(request.headers["authorization"],request.url==="https://api.github.com/user"?`Bearer ${CANARY_TOKEN}`:undefined);w.clock.clean();capture(result);});
  it("malformed overbound manifest and unresolved targets refuse before ports or credentials",async()=>{await baseline();let callbacks=0;const options:LivePreflightOptions={get transport():HttpTransport{callbacks++;throw new Error(CANARY_TOKEN);},get timing():Timing{callbacks++;throw new Error(CANARY_TOKEN);},get credential():string{callbacks++;throw new Error(CANARY_TOKEN);}};for(const bytes of [new Uint8Array(),new Uint8Array(1024*1024+1),canonicalBytes({...fixture(),organization:{login:organization,id:"0"}})]){assert.throws(()=>new LiveInfrastructurePreflight(bytes,organization,options),error=>{capture(error);return error instanceof Error&&error.message==="live-preflight: preflight-refused";});}assert.equal(callbacks,0);});
  it("fresh organization numeric identity canonical login and Organization type are mandatory",async()=>{await baseline();for(const change of [{id:12},{login:"other"},{type:"User"}]){const w=new World();w.change(`https://api.github.com/orgs/${organization}`,value=>Object.assign(value,change));await refused(()=>w.client().read());w.clock.clean();}});
  it("upstream and fork must remain fixed public main repositories owned by the same numeric organization",async()=>{await baseline();for(const url of [prefix,forkPrefix])for(const change of [{id:99},{name:"foreign"},{full_name:"attacker/pixelwatch-m2-live"},{private:true},{visibility:"private"},{default_branch:"other"},{owner:{...owner(),id:12}},{owner:{...owner(),type:"User"}}]){const w=new World();w.change(url,value=>Object.assign(value,change));await refused(()=>w.client().read());w.clock.clean();}});
  it("genuine fork parent and source must each identify the exact separately verified upstream",async()=>{await baseline();for(const section of ["parent","source"])for(const change of [{id:99},{full_name:"attacker/pixelwatch-m2-live"},{private:true}]){const w=new World();w.change(forkPrefix,value=>{value[section]={...repo("pixelwatch-m2-live",20),...change};});await refused(()=>w.client().read());w.clock.clean();}for(const url of [prefix,forkPrefix]){const w=new World();w.change(url,value=>{value["fork"]=url===prefix;});await refused(()=>w.client().read());w.clock.clean();}});
  it("configured numeric source and report workflows must have their exact active paths",async()=>{await baseline();for(const id of [30,31])for(const change of [{id:99},{path:".github/workflows/foreign.yml"},{state:"disabled_manually"}]){const w=new World();w.change(`${prefix}/actions/workflows/${String(id)}`,value=>Object.assign(value,change));await refused(()=>w.client().read());w.clock.clean();}});
  it("actual Pages workflow build canonical public HTTPS URL and no custom domain are required",async()=>{await baseline();for(const change of [{html_url:SIGNED_URL},{html_url:`http://${organization}.github.io/pixelwatch-m2-live/`},{build_type:"legacy"},{build_type:undefined},{cname:"foreign.example"},{https_enforced:false},{public:false}]){const w=new World();w.change(`${prefix}/pages`,value=>{Object.assign(value,change);if(value["build_type"]===undefined)delete value["build_type"];});await refused(()=>w.client().read());w.clock.clean();}});
  it("github-pages environment numeric identity and explicit custom branch policy are required",async()=>{await baseline();for(const change of [{id:99},{name:"foreign"},{deployment_branch_policy:null},{deployment_branch_policy:{protected_branches:true,custom_branch_policies:false}},{deployment_branch_policy:{protected_branches:false,custom_branch_policies:false}}]){const w=new World();w.change(`${prefix}/environments/github-pages`,value=>Object.assign(value,change));await refused(()=>w.client().read());w.clock.clean();}});
  it("complete policy history proves one typed literal main branch and refuses missing tag wildcard or extra rules",async()=>{await baseline();for(const branch_policies of [[],[{id:41,name:"main"}],[{id:41,name:"main",type:"tag"}],[{id:41,name:"*",type:"branch"}],[{id:41,name:"main",type:"branch"},{id:42,name:"other",type:"branch"}],[{id:41,name:"main",type:"branch"},{id:41,name:"main",type:"branch"}]]){const w=new World();w.overrides.set(policyPath,()=>Promise.resolve(json(200,{total_count:branch_policies.length,branch_policies})));await refused(()=>w.client().read());w.clock.clean();}});
  it("terminal policy count cannot ignore explicit next or future last links and returned URLs never select a request",async()=>{await baseline();for(const link of [`<${policyPath.replace("&page=1","&page=2")}>; rel="next"`,`<${policyPath.replace("&page=1","&page=2")}>; rel="last"`,`<${SIGNED_URL}>; rel="next"`]){const w=new World();w.overrides.set(policyPath,()=>Promise.resolve(json(200,{total_count:1,branch_policies:[{id:41,name:"main",type:"branch"}]},{link})));await refused(()=>w.client().read());assert.ok(w.requests.every(request=>!request.url.includes("blob.simulation")));w.clock.clean();}});
  it("both main refs require their literal name current full SHA and commit object",async()=>{await baseline();for(const url of [`${prefix}/git/ref/heads/main`,`${forkPrefix}/git/ref/heads/main`])for(const change of [{ref:"refs/heads/other"},{object:{type:"tag",sha:sha("f")}},{object:{type:"commit",sha:"main"}}]){const w=new World();w.change(url,value=>Object.assign(value,change));await refused(()=>w.client().read());w.clock.clean();}});
  it("public and authenticated bot ID login and User type must match without accepting installation identities",async()=>{await baseline();for(const url of [`https://api.github.com/users/${bot}`,"https://api.github.com/user"])for(const change of [{id:99},{login:"foreign"},{type:"Bot"}]){const w=new World();w.change(url,value=>Object.assign(value,change));await refused(()=>w.client(CANARY_TOKEN).read());w.clock.clean();}});
  it("redirect refusal never follows Location and fixed errors never retain secret response data",async()=>{await baseline();for(const status of [301,302,303,307,308,404,410]){const w=new World();w.overrides.set(`https://api.github.com/orgs/${organization}`,()=>Promise.resolve(json(status,{message:CANARY_TOKEN},{location:SIGNED_URL})));await refused(()=>w.client().read());assert.equal(w.requests.length,1);w.clock.clean();}});
  it("one MiB native JSON and 1024 policy collection bounds reject before success",async()=>{await baseline();const oversized=new Uint8Array(1024*1024+1);let callbacks=0;Object.defineProperty(oversized,"byteLength",{get(){callbacks++;throw new Error(CANARY_TOKEN);}});const w=new World();w.overrides.set(`https://api.github.com/orgs/${organization}`,()=>Promise.resolve({status:200,headers:{},body:oversized}));await refused(()=>w.client().read());assert.equal(callbacks,0);w.clock.clean();const more=new World();more.overrides.set(policyPath,()=>Promise.resolve(json(200,{total_count:1025,branch_policies:[{id:41,name:"main",type:"branch"}]})));await refused(()=>more.client().read());more.clock.clean();});
  it("retry attempts and delays remain bounded and all actual GETs share the instance budget",async()=>{await baseline();const w=new World();let reached=0;w.overrides.set(`https://api.github.com/orgs/${organization}`,()=>{reached++;return Promise.resolve(reached<3?json(reached===1?429:503,{},{"retry-after":"1"}):w.response(`https://api.github.com/orgs/${organization}`));});const client=w.client();await client.read();assert.equal(w.requests.length,13);assert.deepEqual(w.clock.delays,[1000,1000]);w.clock.clean();const exhausted=new World();exhausted.overrides.set(`https://api.github.com/orgs/${organization}`,()=>Promise.resolve(json(500,{message:CANARY_TOKEN})));await refused(()=>exhausted.client().read());assert.equal(exhausted.requests.length,3);assert.deepEqual(exhausted.clock.delays,[1000,2000]);exhausted.clock.clean();});
  it("concurrent reads cannot exceed sixty actual GET attempts across completed and pending calls",async()=>{await baseline();const w=new World(),client=w.client();for(let index=0;index<5;index++)await client.read();assert.equal(w.requests.length,55);const pending=await Promise.allSettled([client.read(),client.read()]);assert.equal(w.requests.length,60);for(const result of pending){assert.equal(result.status,"rejected");capture(result.reason);assert.equal((result.reason as Error).message,"live-preflight: preflight-refused");}w.clock.clean();});
  it("caller cancellation settles an ignored transport with native shadow properties and complete disposal",async()=>{await baseline();const w=new World(),caller=new AbortController();let callbacks=0;Object.defineProperty(caller.signal,"aborted",{get(){callbacks++;throw new Error(CANARY_TOKEN);}});Object.defineProperty(caller.signal,"addEventListener",{get(){callbacks++;throw new Error(CANARY_TOKEN);}});w.overrides.set(`https://api.github.com/orgs/${organization}`,()=>new Promise<HttpResponse>(()=>{}));const pending=w.client().read(caller.signal),observed=refused(()=>pending);for(let index=0;index<30;index++)await Promise.resolve();assert.equal(w.requests.length,1);caller.abort();await observed;assert.equal(callbacks,0);w.clock.clean();});
  it("partial deadline acquisition disposes once and issues no GET when native signal capture fails",async()=>{await baseline();const w=new World();let disposed=0;const timing:Timing={deadline:()=>({get signal():AbortSignal{throw new Error(CANARY_TOKEN);},dispose(){disposed++;}}),delay:()=>Promise.resolve()};await refused(()=>new LiveInfrastructurePreflight(canonicalBytes(fixture()),organization,{transport:w,timing}).read());assert.equal(disposed,1);assert.equal(w.requests.length,0);});
  it("captured transport timing and native response bytes stay owned across calls and later callbacks",async()=>{await baseline();const w=new World(),client=w.client();w.request=()=>{throw new Error(CANARY_TOKEN);};w.clock.deadline=()=>{throw new Error(CANARY_TOKEN);};w.clock.delay=()=>{throw new Error(CANARY_TOKEN);};const first=await client.read(),second=await client.read();assert.equal(first.getAttempts,11);assert.equal(second.getAttempts,22);assert.equal(w.requests.length,22);w.clock.clean();const bytes=canonicalBytes({id:10,login:organization,type:"Organization"});let callbacks=0;for(const key of ["byteLength","buffer","constructor","subarray"])Object.defineProperty(bytes,key,{get(){callbacks++;throw new Error(CANARY_TOKEN);}});const body=new World();body.overrides.set(`https://api.github.com/orgs/${organization}`,()=>{const pending=Promise.resolve({status:200,headers:{},body:bytes});const marked=Object.defineProperty(pending,"then",{get(){callbacks++;throw new Error(CANARY_TOKEN);}});return marked;});await body.client().read();assert.equal(callbacks,0);body.clock.clean();capture(first);capture(second);});
  it("native unlink hook refusal still settles caller and deadline cancellation without raw causes",async()=>{await baseline();for(const useCaller of [true,false]){const w=new World(),caller=new AbortController(),unlink=nativeHook("kRemoveListener");assert.ok(unlink);const client=w.client();w.overrides.set(`https://api.github.com/orgs/${organization}`,()=>new Promise<HttpResponse>(()=>{}));const pending=client.read(useCaller?caller.signal:undefined),observed=refused(()=>pending);for(let index=0;index<30;index++)await Promise.resolve();assert.equal(w.requests.length,1);const target=useCaller?caller:w.clock.handles.find(handle=>handle.ms===600000)?.controller;assert.ok(target);let unlinks=0;Object.defineProperty(target.signal,unlink,{value:()=>{unlinks++;throw new Error(CANARY_TOKEN);}});target.abort();await observed;assert.ok(unlinks>=1);w.clock.clean();}});
  it("ten minute outer expiry refuses a new GET after a late first response and disposes every deadline",async()=>{await baseline();const w=new World();let respond:((response:HttpResponse)=>void)|undefined;w.overrides.set(`https://api.github.com/orgs/${organization}`,()=>new Promise<HttpResponse>(resolve=>{respond=resolve;}));const pending=w.client().read(),observed=refused(()=>pending);for(let index=0;index<30;index++)await Promise.resolve();assert.equal(w.requests.length,1);const outer=w.clock.handles.find(handle=>handle.ms===600000);assert.ok(outer);assert.ok(respond);outer.controller.abort();await observed;respond(w.response(`https://api.github.com/orgs/${organization}`));for(let index=0;index<30;index++)await Promise.resolve();assert.equal(w.requests.length,1);w.clock.clean();});
  it("complete page one terminal first and last links are accepted while contradictory duplicate or foreign metadata refuses",async()=>{for(const link of [`<${policyPath}>; rel="last"`,`<${policyPath}>; rel="first"`,`<${policyPath}>; rel="first", <${policyPath}>; rel="last"`]){const w=new World();w.overrides.set(policyPath,()=>Promise.resolve(json(200,{total_count:1,branch_policies:[{id:41,name:"main",type:"branch"}]},{link})));const result=await w.client().read();assert.equal(result.getAttempts,11);assert.equal(w.requests.length,11);assert.equal(result.readyForMutations,false);assert.equal(result.upstreamHead,sha("f"));w.clock.clean();capture(result);}for(const link of [`<${policyPath}>; rel="next"`,`<${policyPath}>; rel="previous"`,`<${policyPath}>; rel="last", <${policyPath}>; rel="last"`,`<${SIGNED_URL}>; rel="last"`,`<${policyPath.replace("&page=1","&page=2")}>; rel="first"`,"",`<${policyPath}>; rel="last"; title="other"`]){const w=new World();w.overrides.set(policyPath,()=>Promise.resolve(json(200,{total_count:1,branch_policies:[{id:41,name:"main",type:"branch"}]},{link})));await refused(()=>w.client().read());assert.equal(w.requests.filter(request=>request.url===policyPath).length,1);assert.ok(w.requests.every(request=>!request.url.includes("blob.simulation")));w.clock.clean();}});
});
