import "../../../tools/lib/no-network.ts";
import assert from "node:assert/strict";
import { inspect } from "node:util";
import { execFileSync } from "node:child_process";
import { mkdtempSync, readFileSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { isAbsolute, join, relative, resolve } from "node:path";
import { afterEach, beforeAll, describe, expect, it } from "vitest";
import { addRun, newStore, runRecordPath } from "@pixelwatch/core";
import { canonicalBytes, parseDocument, type Config, type Run } from "@pixelwatch/schemas";
import { ForgeError, GitHubClient, isOwnedCommentOperation, type CommentResult, type HttpRequest, type HttpResponse, type HttpTransport, type Timing } from "@pixelwatch/forge-github";
import { LocalDirStore, type StoreSnapshot } from "@pixelwatch/store";
import { CANARY_TOKEN, SIGNED_URL, assertNoSecrets } from "../../../tools/simulation/capture.ts";
import { prepareProjection, finishProjection, renderProjectionSummary } from "../src/projection.ts";
import { PublisherError, type PreparedProjection, type ProjectionFinishDependencies, type ProjectionPrepareDependencies, type ProjectionPrepareInput } from "../src/types.ts";
const REPO="987654321", HEAD="1".repeat(40), CONFIG="2".repeat(40), RELEASE="3".repeat(40), API="https://api.github.com/repos/owner/repo";
const raw:(string|Uint8Array)[]=[];const roots:string[]=[];
let fixtureScript: Uint8Array;
beforeAll(() => {
  const env: Record<string, string> = {};
  for (const key of ["PATH", "SystemRoot", "WINDIR", "TEMP", "TMP"]) {
    const value = process.env[key]; if (value !== undefined) env[key] = value;
  }
  const builder = new URL("../../../tools/viewer/build.ts", import.meta.url).href;
  const script = `const {buildViewerAssets}=await import(${JSON.stringify(builder)});const assets=await buildViewerAssets("0.1.0-rc.1");process.stdout.write(Buffer.from(assets.script).toString("base64"));`;
  const output = execFileSync(process.execPath, ["--import", new URL("../../../tools/lib/no-network.ts", import.meta.url).href, "--input-type=module", "--eval", script], {env, encoding:"utf8", maxBuffer:32*1024*1024, windowsHide:true});
  raw.push(output); assertNoSecrets(raw); fixtureScript = new Uint8Array(Buffer.from(output,"base64"));
});
afterEach(()=>{assertNoSecrets(raw);raw.length=0;for(const root of roots.splice(0)){const rel=relative(resolve(tmpdir()),resolve(root));assert.ok(!isAbsolute(rel)&&/^pixelwatch-projection-[A-Za-z0-9_-]+$/.test(rel));rmSync(root,{recursive:true,force:true});}});
const json=(status:number,value:unknown):HttpResponse=>({status,headers:{},body:canonicalBytes(value)});
function run(id:string,pr:string,head=HEAD):Run {const parsed=parseDocument("run",readFileSync(new URL("../../../testdata/schemas/run/valid/no-usable-artifact.json",import.meta.url)));assert.ok(parsed.ok);return {...parsed.value,runKey:`${id}-a1`,source:{...parsed.value.source,runId:id,event:"pull_request",association:{status:"corroborated",prNumber:pr},commits:{head}}};}
class Clock implements Timing {
  now=0;handles:{controller:AbortController,due:number,closed:boolean}[]=[];delays:number[]=[];delayHook?:()=>void;
  deadline(ms:number){const h={controller:new AbortController(),due:this.now+ms,closed:false};this.handles.push(h);return{signal:h.controller.signal,dispose(){expect(h.closed).toBe(false);h.closed=true;}};}
  advance(ms:number){this.now+=ms;for(const h of this.handles)if(!h.closed&&h.due<=this.now)h.controller.abort();}
  delay(ms:number,signal?:AbortSignal){
    this.delays.push(ms);const end=this.now+ms;
    while(this.now<end&&!signal?.aborted){
      let next=end;for(const handle of this.handles)if(!handle.closed&&!handle.controller.signal.aborted&&handle.due>=this.now&&handle.due<next)next=handle.due;
      this.advance(next-this.now);
    }
    this.delayHook?.();return Promise.resolve();
  }
  clean(){expect(this.handles.every(h=>h.closed)).toBe(true);}
}
class World implements HttpTransport {
  config:Config={schemaVersion:1,source:{workflowIds:["123456"],events:["pull_request"]},providers:[{id:"fixture",shards:1}]};
  timing=new Clock();trace:string[]=[];prs=new Map<string,{state:"open"|"closed",headSha:string}>();comments=new Map<string,{id:number,body:string}>();writes:string[]=[];closeCount=0;
  served?:PreparedProjection;siteReply?:HttpResponse;rootReply=json(404,{});prior:string[]=[];mutationReplies:number[]=[];prHook?:()=>void;snapshotHook?:(snapshot:StoreSnapshot)=>StoreSnapshot;
  repository={repositoryId:REPO,owner:"owner",name:"repo",defaultBranch:"main"};store:LocalDirStore;forge:GitHubClient;input!:ProjectionPrepareInput;
  constructor(){const root=mkdtempSync(join(tmpdir(),"pixelwatch-projection-"));roots.push(root);this.store=new LocalDirStore({directory:join(root,"store"),repositoryId:REPO,defaultBranch:"main"});this.forge=new GitHubClient({owner:"owner",repo:"repo",repositoryId:REPO,token:CANARY_TOKEN,transport:this,timing:this.timing});}
  async init(records:Run[]){this.input={repository:{repositoryId:REPO,owner:"owner",name:"repo"},assets:{release:"0.1.0-rc.1",script:new Uint8Array(fixtureScript),releaseCommit:RELEASE},report:{runId:"900",attempt:1,workflowPath:".github/workflows/report.yml",workflowId:"789",headSha:CONFIG,ref:"refs/heads/main",runnerName:"GitHub Actions 1"}};
    let store=newStore(REPO);const runs=new Map<string,Run>();const files=new Map<string,Uint8Array>();for(const record of records){store=addRun(store,record).store;runs.set(record.runKey,record);files.set(runRecordPath(record.runKey),canonicalBytes(record));const pr=record.source.association.prNumber;if(pr!==undefined)this.prs.set(pr,{state:"open",headSha:record.source.commits.head??HEAD});}files.set("store.json",canonicalBytes(store));expect((await this.store.cas(null,{store,runs,files,metadata:{timestamp:"2026-10-03T00:00:00Z"}})).status).toBe("accepted");return this;}
  request(request:HttpRequest):Promise<HttpResponse>{assert.notEqual(request.signal?.aborted,true);let response:HttpResponse;
    if(request.url.startsWith("https://api.github.com/")){expect(request.headers["authorization"]).toBe(`Bearer ${CANARY_TOKEN}`);
      const repo={id:Number(REPO),owner:{login:"owner"},name:"repo",full_name:"owner/repo",default_branch:this.repository.defaultBranch};const path=request.url.slice(API.length);
      if(request.url==="https://api.github.com/users/github-actions%5Bbot%5D"){this.trace.push("bot");response=json(200,{id:41898282,login:"github-actions[bot]",type:"Bot"});}
      else if(path===""){this.trace.push("repository");response=json(200,repo);}
      else if(path===`/git/ref/heads/${this.repository.defaultBranch}`){this.trace.push("config-ref");response=json(200,{ref:`refs/heads/${this.repository.defaultBranch}`,object:{type:"commit",sha:CONFIG}});}
      else if(path===`/contents/.pixelwatch/config.json?ref=${CONFIG}`){this.trace.push("config");response=json(200,this.config);}
      else if(path==="/pages"){this.trace.push("pages");response=json(200,{build_type:"workflow",html_url:"https://owner.github.io/repo/",cname:null});}
      else if(/^\/pulls\/[0-9]+$/.test(path)){const pr=path.split("/")[2];assert.ok(pr);this.prHook?.();this.trace.push("pr:"+pr);const value=this.prs.get(pr);response=value===undefined?json(404,{}):json(200,{number:Number(pr),state:value.state,head:{sha:value.headSha,repo:{id:123}},base:{repo:{id:Number(REPO)}}});}
      else if(/^\/issues\/[0-9]+\/comments\?per_page=100&page=1$/.test(path)){const pr=path.split("/")[2];assert.ok(pr);this.trace.push("discover:"+pr);const c=this.comments.get(pr);response=json(200,c===undefined?[]:[{id:c.id,body:c.body,user:{id:41898282}}]);}
      else if(request.method==="POST"||request.method==="PATCH"){const pr=request.method==="POST"?path.split("/")[2]: [...this.comments].find(([,c])=>String(c.id)===path.split("/").at(-1))?.[0];assert.ok(pr);this.trace.push("write:"+pr);this.writes.push(pr);const status=this.mutationReplies.shift()??201;if(status===422)response=json(422,{message:CANARY_TOKEN+SIGNED_URL});else{assert.ok(request.body);const payload=JSON.parse(Buffer.from(request.body).toString()) as {body:string};const c={id:this.comments.get(pr)?.id??500+Number(pr),body:payload.body};this.comments.set(pr,c);response=json(request.method==="POST"?201:200,{...c,user:{id:41898282}});}}
      else throw new Error("unregistered API request");
    }else{expect(Object.keys(request.headers).map(v=>v.toLowerCase())).not.toContain("authorization");this.trace.push("served:"+request.url);
      if(request.url==="https://owner.github.io/repo/")response=this.rootReply;
      else{const path=request.url.slice("https://owner.github.io/repo/pixelwatch/".length);const file=this.served?.site.files.find(f=>f.path===path);response=file===undefined?(this.siteReply??json(404,{})):{status:200,headers:{},body:file.bytes};}}
    return Promise.resolve({...response,body:new Uint8Array(response.body)});
  }
  prepareDeps():ProjectionPrepareDependencies{return{forge:this.forge,metadata:{readEnvironment:(branch)=>{this.trace.push("environment");return Promise.resolve({environmentId:"777",defaultBranch:branch});},readDeploymentHistory:()=>{this.trace.push("history");return Promise.resolve({current:{deploymentId:"42",jobId:"9000",states:["queued"]},priorDeploymentIds:[...this.prior],complete:true});}},openStore:input=>{this.trace.push("open-store");expect(input).toEqual({repository:this.input.repository,defaultBranch:"main",branch:"pixelwatch-data"});return Promise.resolve({store:{read:async()=>{this.trace.push("store-read");const s=await this.store.read();return this.snapshotHook?.(s)??s;}},close:()=>{this.closeCount++;}});},transport:this,timing:this.timing};}
  finishDeps():ProjectionFinishDependencies{return{forge:this.forge,readiness:{transport:this,timing:this.timing,now:()=>this.timing.now}};}
}
async function prepared(w:World){const result=await prepareProjection(w.input,w.prepareDeps());raw.push(JSON.stringify(result));assertNoSecrets(raw);expect(result.status).toBe("prepared");assert.equal(result.status,"prepared");return result.projection;}
async function finish(w:World,p:PreparedProjection,outcome:"success"|"failure"|"cancelled"="success"){w.served=p;const result=await finishProjection(p,{outcome},w.finishDeps());raw.push(JSON.stringify(result),renderProjectionSummary(result));assertNoSecrets(raw);return result;}
async function refuses(operation:()=>Promise<unknown>,code?:string){let error:unknown;try{await operation();}catch(caught){error=caught;}expect(error).toBeInstanceOf(PublisherError);raw.push(inspect(error,{showHidden:true,depth:20}));assertNoSecrets(raw);if(code!==undefined)expect((error as PublisherError).code).toBe(code);}
describe("serialized production projection caller",()=>{
  it("projection reads fresh config and store only after the workflow-held lock",async()=>{const w=await new World().init([run("101","7")]);w.config={...w.config,theme:{preset:"github-dark"}};const p=await prepared(w);expect(w.trace.indexOf("config")).toBeLessThan(w.trace.indexOf("open-store"));expect(w.trace.indexOf("store-read")).toBeGreaterThan(w.trace.indexOf("pages"));expect(p.context.config.theme?.preset).toBe("github-dark");expect(p.context.configCommit).toBe(CONFIG);expect(p.site.storeTip).toBe((await w.store.read()).tip);expect(w.closeCount).toBe(1);w.timing.clean();});
  it("coalesced projection repairs every eligible retained PR",async()=>{const w=await new World().init([run("101","7"),run("102","8")]);const p=await prepared(w);expect(p.targets.map(t=>t.prNumber)).toEqual(["7","8"]);const result=await finish(w,p);expect(result.comments.map(c=>[c.prNumber,c.status])).toEqual([["7","created"],["8","created"]]);expect(w.writes).toEqual(["7","8"]);expect(result.readiness.status).toBe("served");w.timing.clean();});
  it("pointer mismatch and unavailable PR state defer without rewriting pointer bytes",async()=>{const w=await new World().init([run("101","7"),run("102","7","4".repeat(40)),run("103","8")]);w.prs.set("7",{state:"open",headSha:HEAD});w.prs.delete("8");const p=await prepared(w);expect(p.targets).toEqual([]);expect(p.deferred).toEqual([{prNumber:"7",reason:"pointer-mismatch"},{prNumber:"8",reason:"pr-unavailable"}]);const pointer=p.site.files.find(f=>f.path==="api/v1/pr/7/latest.json");assert.ok(pointer);expect((JSON.parse(Buffer.from(pointer.bytes).toString()) as {runKey:string}).runKey).toBe("102-a1");expect(w.writes).toEqual([]);});
  it("unknown prepared config store and run versions refuse before deployment or comments",async()=>{for(const kind of ["config","store","run"]){const w=await new World().init([run("101","7")]);if(kind==="config")Object.assign(w.config,{schemaVersion:2});else w.snapshotHook=s=>kind==="store"?{...s,store:{...s.store,schemaVersion:2} as never}:{...s,runs:new Map([...s.runs].map(([k,v])=>[k,{...v,schemaVersion:2} as never]))};await refuses(()=>prepared(w));expect(w.writes).toEqual([]);expect(w.trace.some(s=>s.startsWith("served:"))).toBe(false);}});
  it("queued older release observes the newest store without rolling back a comment",async()=>{const w=await new World().init([run("101","7"),run("102","7")]);w.input={...w.input,assets:{...w.input.assets,release:"0.1.0-rc.1"}};const p=await prepared(w);const result=await finish(w,p);expect(result.comments[0]).toMatchObject({runKey:"102-a1",status:"created"});const siteFile=p.site.files.find(f=>f.path==="site.json");assert.ok(siteFile);expect((JSON.parse(Buffer.from(siteFile.bytes).toString()) as {versions:{release:string}}).versions.release).toBe("0.1.0-rc.1");const newer=run("103","7");w.comments.set("7",{id:507,body:`<!-- pixelwatch:repo:${REPO} -->\n<!-- pixelwatch:report:v1:${newer.runKey}:${HEAD}:${"f".repeat(64)} -->`});const again=await finish(w,p);expect(again.comments[0]).toMatchObject({status:"deferred",reason:"comment-order-unproved"});expect(w.writes).toHaveLength(1);});
  it("head changes during retry backoff defer sticky mutation",async()=>{const w=await new World().init([run("101","7")]);const p=await prepared(w);w.mutationReplies=[503];w.timing.delayHook=()=>{if(w.writes.length>0)w.prs.set("7",{state:"open",headSha:"4".repeat(40)});};const original=w.request.bind(w);w.request=(request)=>request.method==="POST"&&w.writes.length===0?(w.writes.push("7"),Promise.resolve(json(503,{}))):original(request);const result=await finish(w,p);expect(result.comments[0]).toMatchObject({status:"deferred",reason:"head-changed"});expect(w.writes).toEqual(["7"]);});
  it("failed and cancelled deployment outcomes cannot substitute for served-byte proof",async()=>{for(const outcome of ["failure","cancelled"] as const){const w=await new World().init([run("101","7")]);const p=await prepared(w);const unserved=await finishProjection(p,{outcome},w.finishDeps());expect(unserved.readiness.status).toBe("pending");expect(w.writes).toEqual([]);const landed=await finish(w,p,outcome);expect(landed.deployment).toBe(outcome);expect(landed.readiness.status).toBe("served");expect(landed.comments[0]?.status).toBe("created");w.timing.clean();}});
  it("exact served generation precedes every comment mutation",async()=>{const w=await new World().init([run("101","7")]);const p=await prepared(w);await finish(w,p);const first=w.trace.indexOf("write:7");expect(w.trace.slice(0,first).filter(s=>s==="served:https://owner.github.io/repo/pixelwatch/site.json")).toHaveLength(7);expect(w.timing.delays.slice(0,4)).toEqual([10000,10000,10000,10000]);expect(w.trace.indexOf("bot")).toBeLessThan(first);});
  it("definitive comment refusal makes exactly one freshly guarded fallback attempt",async()=>{const w=await new World().init([run("101","7")]);const p=await prepared(w);w.mutationReplies=[422];const result=await finish(w,p);expect(result.comments[0]?.status).toBe("created");expect(w.writes).toEqual(["7","7"]);expect(w.comments.get("7")?.body).toContain("Full report: https:");expect(w.trace.filter(s=>s==="pr:7")).toHaveLength(3);});
  it("malformed foreign changed or stale prepared state refuses before mutation",async()=>{for(const mode of ["body","generation","namespace","unknown"]){const w=await new World().init([run("101","7")]);const p=await prepared(w);const changed={...p,site:{...p.site,files:p.site.files.map(f=>({...f,bytes:new Uint8Array(f.bytes)}))}};if(mode==="body"){const entry=changed.site.files.find(f=>f.path==="index.html");assert.ok(entry);entry.bytes[0]=(entry.bytes[0]??0)^1;}else if(mode==="generation")changed.site.generation="a".repeat(64);else if(mode==="namespace")changed.context={...p.context,repository:{...p.context.repository,repositoryId:"42"}};else Object.assign(changed,{schemaVersion:2});await refuses(()=>finish(w,changed));expect(w.writes).toEqual([]);}});
  it("unknown or expired owned stamps cannot certify source-order rollback",async()=>{for(const body of [`<!-- pixelwatch:repo:${REPO} --> unrecognized`,`<!-- pixelwatch:repo:${REPO} -->\n<!-- pixelwatch:report:v2:101-a1:${HEAD}:${"a".repeat(64)} -->`,`<!-- pixelwatch:repo:${REPO} -->\n<!-- pixelwatch:report:v1:1-a1:${HEAD}:${"a".repeat(64)} -->`]){const w=await new World().init([run("101","7")]);const p=await prepared(w);w.comments.set("7",{id:507,body});const result=await finish(w,p);expect(result.comments[0]).toMatchObject({status:"deferred",reason:"comment-order-unproved"});expect(w.writes).toEqual([]);}});
  it("ignored ports and partial cleanup cannot strand bounded projection",async()=>{const w=await new World().init([run("101","7")]);const dependencies={...w.prepareDeps(),openStore:()=>new Promise<Awaited<ReturnType<ProjectionPrepareDependencies["openStore"]>>>(()=>{})};const pending=prepareProjection(w.input,dependencies);for(let i=0;i<30;i++)await Promise.resolve();w.timing.advance(600000);await refuses(()=>pending,"projection-cancelled");w.timing.clean();expect(w.writes).toEqual([]);});
  it("prepare captures native map entries and file bytes before later microtasks",async()=>{const w=await new World().init([run("101","7")]);w.snapshotHook=s=>{const runs=new Map(s.runs);Object.defineProperty(runs,Symbol.iterator,{value:()=>{throw new Error(CANARY_TOKEN);}});const reader=s.readFile.bind(s);return {...s,runs,readFile:path=>new Promise<Uint8Array>((resolve,reject)=>{void reader(path).then(bytes=>{resolve(bytes);queueMicrotask(()=>bytes.fill(0));},reject);})};};const p=await prepared(w);expect(p.records[0]?.runKey).toBe("101-a1");expect(p.site.files.find(f=>f.path===runRecordPath("101-a1"))?.bytes.byteLength).toBeGreaterThan(0);w.timing.clean();});
  it("complete unused-site proof refuses redirects positive roots and prior deployments",async()=>{for(const mode of ["root","redirect","prior"]){const w=await new World().init([run("101","7")]);if(mode==="root")w.rootReply=json(200,{});else if(mode==="redirect")w.siteReply={status:302,headers:{location:SIGNED_URL},body:new Uint8Array()};else w.prior=["41"];await refuses(()=>prepared(w),"projection-site-ownership-refused");expect(w.writes).toEqual([]);expect(w.closeCount).toBe(1);w.timing.clean();}});
  it("cleanup warnings preserve prepared served and accepted outcomes",async()=>{const w=await new World().init([run("101","7")]);const deps=w.prepareDeps();const result=await prepareProjection(w.input,{...deps,openStore:async input=>{const opened=await deps.openStore(input);return {...opened,close:async()=>{await opened.close();throw new Error(CANARY_TOKEN+SIGNED_URL);}};}});expect(result.status).toBe("prepared");assert.equal(result.status,"prepared");expect(result.projection.warnings).toEqual(["store-close-failed"]);w.served=result.projection;const original=w.timing.deadline.bind(w.timing);const finishDeps=w.finishDeps();const timing:Timing={deadline:ms=>{const h=original(ms);return {...h,dispose(){h.dispose();throw new Error(CANARY_TOKEN+SIGNED_URL);}};},delay:ms=>w.timing.delay(ms)};const done=await finishProjection(result.projection,{outcome:"success"},{...finishDeps,readiness:{...finishDeps.readiness,timing}});raw.push(JSON.stringify(done),renderProjectionSummary(done));expect(done.readiness.status).toBe("served");expect(done.comments[0]?.status).toBe("created");expect(done.warnings).toEqual(["store-close-failed","timing-disposal-failed"]);w.timing.clean();});
  it("restored state rebuilds exact assembly and ignores persisted URL methods",async()=>{const w=await new World().init([run("101","7")]);const p=await prepared(w);const restored=structuredClone({...p,site:{...p.site,urls:undefined}}) as unknown as PreparedProjection;Object.assign(restored.site,{urls:{siteJson:()=>SIGNED_URL}});const result=await finish(w,restored);expect(result.comments[0]?.status).toBe("created");expect(w.trace.some(v=>v.includes(SIGNED_URL))).toBe(false);});
  it("a later store run cannot replace the prepared served target",async()=>{const w=await new World().init([run("101","7")]);const p=await prepared(w);const later=run("102","7");const before=await w.store.read();const bytes=new Map<string,Uint8Array>();for(const file of before.files)bytes.set(file.path,await before.readFile(file.path));const next=addRun(before.store,later).store;bytes.set("store.json",canonicalBytes(next));bytes.set(runRecordPath(later.runKey),canonicalBytes(later));expect((await w.store.cas(before.tip,{store:next,runs:new Map([...before.runs,[later.runKey,later]]),files:bytes,metadata:{timestamp:"2026-10-03T00:00:01Z"}})).status).toBe("accepted");const done=await finish(w,p);expect(done.comments[0]).toMatchObject({runKey:"101-a1",status:"created"});expect(w.comments.get("7")?.body).toContain("101-a1");expect(w.comments.get("7")?.body).not.toContain("102-a1");});
  it("outer expiry after served observation preserves proof and starts no comment mutation",async()=>{const w=await new World().init([run("101","7")]);const p=await prepared(w);w.served=p;const deps=w.finishDeps();const original=w.timing.deadline.bind(w.timing);let overall=0;const timing:Timing={deadline:ms=>{const h=original(ms);const ordinal=ms===600000?++overall:0;return {...h,dispose(){h.dispose();if(ordinal===2)w.timing.advance(600000);}};},delay:ms=>w.timing.delay(ms)};const done=await finishProjection(p,{outcome:"success"},{...deps,readiness:{...deps.readiness,timing}});raw.push(JSON.stringify(done));expect(done.readiness.status).toBe("served");expect(done.comments[0]?.status).not.toBe("created");expect(w.writes).toEqual([]);w.timing.clean();});
  it("late store acquisition after cancellation is closed once without a late read",async()=>{const w=await new World().init([run("101","7")]);type Opened=Awaited<ReturnType<ProjectionPrepareDependencies["openStore"]>>;let release:(value:Opened)=>void=()=>{throw new Error("not acquired");};let called=false;const deps=w.prepareDeps();const pending=prepareProjection(w.input,{...deps,openStore:()=>{called=true;return new Promise<Opened>(resolve=>{release=resolve;});}});void pending.catch(()=>undefined);for(let i=0;i<100;i++)await Promise.resolve();expect(called).toBe(true);w.timing.advance(600000);await refuses(()=>pending,"projection-cancelled");let reads=0;release({store:{read:()=>{reads++;return w.store.read();}},close:()=>{w.closeCount++;}});for(let i=0;i<30;i++)await Promise.resolve();expect(w.closeCount).toBe(1);expect(reads).toBe(0);w.timing.clean();});
  // eslint-disable-next-line @typescript-eslint/prefer-promise-reject-errors -- Deliberately hostile ports may reject with undefined; that must remain a refusal.
  it("undefined port rejection is refused before store acquisition",async()=>{const w=await new World().init([run("101","7")]);const deps=w.prepareDeps();await refuses(()=>prepareProjection(w.input,{...deps,metadata:{...deps.metadata,readEnvironment:()=>Promise.reject(undefined)}}),"projection-operation-failed");expect(w.trace).not.toContain("open-store");expect(w.writes).toEqual([]);w.timing.clean();});
  it("fabricated and replayed comment refusal diagnostics cannot authorize a new fallback",async()=>{for(const mode of ["fabricated","replayed"]){const w=await new World().init([run("101","7")]);const p=await prepared(w);w.served=p;const actual=w.forge.reconcileComment.bind(w.forge);let rejection:unknown=new ForgeError("comment-body-rejected");if(mode==="replayed"){w.mutationReplies=[422];try{await actual({prNumber:"7",botId:"41898282",body:`<!-- pixelwatch:repo:${REPO} --> earlier refused request`,beforeMutation:()=>Promise.resolve(true)});}catch(error){rejection=error;}expect(rejection).toBeInstanceOf(ForgeError);expect((rejection as ForgeError).code).toBe("comment-body-rejected");}assert.ok(rejection instanceof ForgeError);const before=w.writes.length;let calls=0;const deps=w.finishDeps();const result=await finishProjection(p,{outcome:"success"},{...deps,forge:{getRepository:w.forge.getRepository.bind(w.forge),getPullRequest:w.forge.getPullRequest.bind(w.forge),getPublishingBot:w.forge.getPublishingBot.bind(w.forge),reconcileComment:input=>{calls++;return calls===1?Promise.reject(rejection):actual(input);}}});raw.push(JSON.stringify(result),inspect(rejection,{showHidden:true,depth:20}));expect(calls).toBe(1);expect(w.writes).toHaveLength(before);expect(result.comments[0]).toMatchObject({status:"failed",reason:"comment-operation-failed"});expect(w.comments.size).toBe(0);w.timing.clean();}});
  it("reentrant cancellation during store acquisition closes the captured resource once",async()=>{const w=await new World().init([run("101","7")]);const deps=w.prepareDeps(),controller=new AbortController();let getters=0,closes=0,reads=0;const resource={store:{read:()=>{reads++;return w.store.read();}},get close(){getters++;controller.abort();return()=>{closes++;};}};await refuses(()=>prepareProjection(w.input,{...deps,signal:controller.signal,openStore:()=>Promise.resolve(resource)}),"projection-cancelled");expect(getters).toBe(1);expect(closes).toBe(1);expect(reads).toBe(0);expect(w.writes).toEqual([]);w.timing.clean();});
  it("expiry during actual accepted reply disposal preserves the received comment outcome",async()=>{const w=await new World().init([run("101","7")]);const p=await prepared(w);w.served=p;const controller=new AbortController(),original=w.timing.deadline.bind(w.timing);let expired=false,actualReply:CommentResult|undefined;w.timing.deadline=ms=>{const handle=original(ms),before=w.writes.length;return {...handle,dispose(){handle.dispose();if(ms===60000&&w.writes.length>before&&!expired){expired=true;controller.abort();}}};};const actual=w.forge.reconcileComment.bind(w.forge),deps=w.finishDeps();const result=await finishProjection(p,{outcome:"success"},{...deps,signal:controller.signal,forge:{getRepository:w.forge.getRepository.bind(w.forge),getPullRequest:w.forge.getPullRequest.bind(w.forge),getPublishingBot:w.forge.getPublishingBot.bind(w.forge),reconcileComment:input=>{const pending=actual(input);void pending.then(value=>{actualReply=value;},()=>undefined);return pending;}}});for(let i=0;i<80;i++)await Promise.resolve();raw.push(JSON.stringify(result),JSON.stringify(actualReply));expect(expired).toBe(true);expect(actualReply?.status).toBe("created");expect(result.readiness.status).toBe("served");expect(result.comments[0]).toMatchObject({status:"created",commentId:"507"});expect(w.writes).toEqual(["7"]);w.timing.clean();});
  it("fresh served proofs guard first retry fallback and coalesced PR mutations",async()=>{for(const mode of ["first","retry","fallback","coalesced"]){const w=await new World().init(mode==="coalesced"?[run("101","7"),run("102","8")]:[run("101","7")]);const p=await prepared(w);w.served=p;const original=w.request.bind(w);let flipped=false;if(mode==="fallback")w.mutationReplies=[422];w.request=request=>{const discovery=request.url.endsWith(`/issues/${mode==="coalesced"?"8":"7"}/comments?per_page=100&page=1`);if(!flipped&&((mode==="first"||mode==="coalesced")&&discovery)){flipped=true;delete w.served;}if(mode==="retry"&&!flipped&&request.method==="POST"){flipped=true;w.writes.push("7");delete w.served;return Promise.resolve(json(503,{}));}const pending=original(request);if(mode==="fallback"&&!flipped&&request.method==="POST"){flipped=true;delete w.served;}return pending;};const result=await finishProjection(p,{outcome:"success"},w.finishDeps());raw.push(JSON.stringify(result));expect(flipped).toBe(true);expect(result.readiness.status).toBe("served");expect(w.writes).toEqual(mode==="first"?[]:["7"]);expect(result.comments.at(-1)).toMatchObject(mode==="retry"?{status:"failed",reason:"comment-operation-failed"}:{status:"deferred",reason:"readiness-pending"});expect(w.timing.now).toBeLessThanOrEqual(600000);w.timing.clean();}});
  it("a wrapper returning the exact current genuine operation retains fresh refusal authority",async()=>{
    const w=await new World().init([run("101","7")]),p=await prepared(w);w.served=p;w.mutationReplies=[422];
    const deps=w.finishDeps(),actual=w.forge.reconcileComment.bind(w.forge);let calls=0;
    const result=await finishProjection(p,{outcome:"success"},{...deps,forge:{...deps.forge,getRepository:w.forge.getRepository.bind(w.forge),getPullRequest:w.forge.getPullRequest.bind(w.forge),getPublishingBot:w.forge.getPublishingBot.bind(w.forge),reconcileComment:input=>{calls++;expect(Object.isFrozen(input)).toBe(true);const pending=actual(input);expect(isOwnedCommentOperation(pending,REPO,input)).toBe(true);return pending;}}});
    raw.push(JSON.stringify(result));expect(calls).toBe(2);expect(w.writes).toEqual(["7","7"]);expect(result.comments[0]).toMatchObject({status:"created",commentId:"507"});w.timing.clean();
  });
  it("cloned aliased and older genuine operations cannot authorize cancellation joins",async()=>{
    for(const mode of ["clone","alias","older"]){
      const w=await new World().init([run("101","7")]),p=await prepared(w);w.served=p;
      const actual=w.forge.reconcileComment.bind(w.forge),caller=new AbortController();let older:Promise<CommentResult>|undefined;
      if(mode==="older"){older=actual(Object.freeze({prNumber:"7",botId:"41898282",body:`<!-- pixelwatch:repo:${REPO} --> previous invocation`,beforeMutation:()=>Promise.resolve(true),signal:new AbortController().signal}));await older;}
      const original=w.timing.deadline.bind(w.timing);w.timing.deadline=ms=>{const handle=original(ms),before=w.writes.length;return {...handle,dispose(){handle.dispose();if(ms===60000&&w.writes.length>before)caller.abort();}};};
      const deps=w.finishDeps();let calls=0;
      const result=await finishProjection(p,{outcome:"success"},{...deps,signal:caller.signal,forge:{getRepository:w.forge.getRepository.bind(w.forge),getPullRequest:w.forge.getPullRequest.bind(w.forge),getPublishingBot:w.forge.getPublishingBot.bind(w.forge),reconcileComment:input=>{calls++;let pending:Promise<CommentResult>;if(mode==="older"){assert.ok(older);pending=older;caller.abort();}else if(mode==="clone")pending=actual(Object.freeze({...input}));else pending=actual(input).then(value=>value);expect(isOwnedCommentOperation(pending,REPO,input)).toBe(false);return pending;}}});
      raw.push(JSON.stringify(result));expect(calls).toBe(1);expect(result.comments[0]).toMatchObject({status:"failed",reason:"comment-operation-failed"});w.timing.clean();
    }
  });
  it("genuine accepted cleanup warnings survive the bounded joined cancellation result",async()=>{
    const w=await new World().init([run("101","7")]),p=await prepared(w);w.served=p;
    const caller=new AbortController(),original=w.timing.deadline.bind(w.timing),holder=Object.getPrototypeOf(Object.getPrototypeOf(new AbortController().signal)) as object;
    const unlink=Object.getOwnPropertySymbols(holder).find(symbol=>symbol.description==="kRemoveListener");assert.ok(unlink);let injected=false;
    w.timing.deadline=ms=>{const handle=original(ms),before=w.writes.length;if(ms===60000&&w.trace.at(-1)==="pr:7")Object.defineProperty(handle.signal,unlink,{value(){throw new Error(CANARY_TOKEN+SIGNED_URL);}});return {...handle,dispose(){handle.dispose();if(ms===60000&&w.writes.length>before){injected=true;caller.abort();throw new Error(CANARY_TOKEN+SIGNED_URL);}}};};
    const result=await finishProjection(p,{outcome:"success"},{...w.finishDeps(),signal:caller.signal});raw.push(JSON.stringify(result));
    expect(injected).toBe(true);expect(result.comments[0]).toMatchObject({status:"created",commentId:"507"});expect(result.warnings).toEqual(["listener-cleanup-failed","timing-disposal-failed"]);expect(w.writes).toEqual(["7"]);w.timing.clean();
  });
  it("an ignored comment port remains bounded without operation completion authority",async()=>{
    const w=await new World().init([run("101","7")]),p=await prepared(w);w.served=p;const deps=w.finishDeps();let reached=false;
    const pending=finishProjection(p,{outcome:"success"},{...deps,forge:{getRepository:w.forge.getRepository.bind(w.forge),getPullRequest:w.forge.getPullRequest.bind(w.forge),getPublishingBot:w.forge.getPublishingBot.bind(w.forge),reconcileComment:()=>{reached=true;return new Promise<CommentResult>(()=>{});}}});
    for(let index=0;index<200;index++)await Promise.resolve();expect(reached).toBe(true);w.timing.advance(600000-w.timing.now);
    const result=await pending;raw.push(JSON.stringify(result));expect(result.readiness.status).toBe("served");expect(result.comments[0]).toMatchObject({status:"failed",reason:"comment-operation-failed"});expect(w.timing.now).toBe(600000);expect(w.writes).toEqual([]);w.timing.clean();
  });
  it("foreign comment cleanup warnings are validated before result accounting",async()=>{
    for(const value of [["unknown"],["timing-disposal-failed","timing-disposal-failed"],["listener-cleanup-failed","timing-disposal-failed","store-close-failed"]]){
      const w=await new World().init([run("101","7")]),p=await prepared(w);w.served=p;const deps=w.finishDeps();
      const result=await finishProjection(p,{outcome:"success"},{...deps,forge:{getRepository:w.forge.getRepository.bind(w.forge),getPullRequest:w.forge.getPullRequest.bind(w.forge),getPublishingBot:w.forge.getPublishingBot.bind(w.forge),reconcileComment:()=>Promise.resolve({status:"created",commentId:"507",warnings:value as never})}});
      raw.push(JSON.stringify(result));expect(result.comments[0]).toMatchObject({status:"failed",reason:"comment-operation-failed"});expect(result.warnings).toBeUndefined();expect(w.writes).toEqual([]);w.timing.clean();
    }
  });
  it("cancellation after an authorized sent attempt cannot become an unsent deferral",async()=>{
    for(const mode of ["lost","503"]){
      const w=await new World().init([run("101","7")]),p=await prepared(w);w.served=p;
      const original=w.request.bind(w);let reached=false;
      w.request=request=>{
        if(request.method==="POST"&&!reached){reached=true;w.writes.push("7");
          if(mode==="lost")return new Promise<HttpResponse>(()=>{});
          delete w.served;return Promise.resolve(json(503,{}));
        }
        return original(request);
      };
      const pending=finishProjection(p,{outcome:"success"},w.finishDeps());
      for(let index=0;index<500;index++)await Promise.resolve();expect(reached).toBe(true);
      if(w.timing.now<600000)w.timing.advance(600000-w.timing.now);
      const result=await pending;raw.push(JSON.stringify(result));expect(result.readiness.status).toBe("served");
      expect(result.comments[0]).toMatchObject({status:"failed",reason:"comment-operation-failed"});expect(w.writes).toEqual(["7"]);expect(w.timing.now).toBe(600000);w.timing.clean();
    }
  });
  it("the deterministic clock interrupts a delay at its armed deadline timestamp",async()=>{
    const clock=new Clock();clock.now=591000;const timing:Timing=clock,handle=clock.deadline(9000);
    try{await timing.delay(10000,handle.signal);expect(handle.signal.aborted).toBe(true);expect(clock.now).toBe(600000);expect(clock.delays).toEqual([10000]);}
    finally{handle.dispose();clock.clean();}
  });
  it("pending deployment and comment summary preserves fixed simulation vocabulary and trusted repair",async()=>{
    for(const outcome of ["failure","cancelled"] as const){
      const w=await new World().init([run("101","7")]),p=await prepared(w);
      const pending=await finishProjection(p,{outcome},w.finishDeps()),summary=renderProjectionSummary(pending);raw.push(JSON.stringify(pending),summary);
      expect(pending.readiness.status).toBe("pending");expect(w.writes).toEqual([]);
      expect(summary).toContain("stored; deployment pending");expect(summary).toContain("repair");
      expect(summary).toContain("Readiness: stored; deployment pending; comment pending");
      expect(summary).toContain("gh workflow run 'report.yml' --ref 'main'");expect(summary).not.toContain("published");
      const repaired=await finish(w,p,outcome),repairedSummary=renderProjectionSummary(repaired);raw.push(repairedSummary);
      expect(repaired.generation).toBe(pending.generation);expect(repaired.storeTip).toBe(pending.storeTip);expect(repaired.deployment).toBe(outcome);
      expect(repaired.readiness.status).toBe("served");expect(repaired.comments[0]).toMatchObject({status:"created",commentId:"507"});
      expect(repairedSummary).toContain("Readiness: served as observed from the runner");expect(w.writes).toEqual(["7"]);w.timing.clean();
    }
  });
});
